name: Canaries

on:
  schedule:
    - cron: '23,53 * * * *'
  workflow_dispatch:

concurrency:
  group: no-dup
  cancel-in-progress: false

jobs:
  canaries:
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ vars.APIKEY }}
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install Latest executables
        run: |
          sudo apt update
          sudo apt install -y binutils pv unzip bc curl wget

          wget -q --no-check-certificate -O /usr/local/bin/jq https://github.com/jqlang/jq/releases/latest/download/jq-linux64
          sudo chmod 755 /usr/local/bin/jq
          jq --version

      - name: Get device list and migrate.sh, aka pifork@osm0sis piggyback XD
        run: |
          mkdir "$GITHUB_WORKSPACE/devices" || true
          mkdir "$GITHUB_WORKSPACE/betas" || true
          mkdir "$GITHUB_WORKSPACE/betas/cinnamonbun" || true
          cd "$GITHUB_WORKSPACE/devices"

          wget -q -O PIXEL_VERSIONS_HTML --no-check-certificate "https://developer.android.com/about/versions" 2>&1 || exit 1;
          wget -q -O PIXEL_LATEST_HTML --no-check-certificate "$(grep -o 'https://developer.android.com/about/versions/.*[0-9]"' PIXEL_VERSIONS_HTML | sort -ru | cut -d\" -f1 | head -n1 | tail -n1)" 2>&1 || exit 1;
          wget -q -O PIXEL_FI_HTML --no-check-certificate "https://developer.android.com$(grep -o 'href=".*download.*"' PIXEL_LATEST_HTML | grep 'qpr' | cut -d\" -f2 | head -n1 | tail -n1)" 2>&1 || exit 1;
          grep -A1 'tr id=' PIXEL_FI_HTML | grep 'td' | sed 's;.*<td>\(.*\)</td>;\1;' > model.list
          PRODUCT_LIST="$(grep 'tr id=' PIXEL_FI_HTML | sed 's;.*<tr id="\(.*\)">;\1_beta;' | tr '\n' ' ')";

          echo "PRODUCTS=$PRODUCT_LIST" >> $GITHUB_ENV

          curl -s -o migrate.sh https://raw.githubusercontent.com/osm0sis/PlayIntegrityFork/refs/heads/main/module/migrate.sh
          sudo chmod +x migrate.sh

          sudo cp -af migrate.sh ../betas/
          sudo cp -af model.list ../betas/
          sudo cp -af migrate.sh ../betas/cinnamonbun/
          sudo cp -af model.list ../betas/cinnamonbun/

      - name: Main
        run: |
          set +e

          cd "$GITHUB_WORKSPACE/devices"

          checkAPI="$( curl -s https://flash.android.com/ | grep -o '<body data-client-config=.*' | cut -d\; -f2 | cut -d\& -f1 )"
          if [[ "$checkAPI" != "$APIKEY" ]]; then
            echo "NEWAPIKEY=$checkAPI" >> $GITHUB_ENV
            echo "NEWAPI=1" >> $GITHUB_ENV
          else
            echo "NEWAPI=0" >> $GITHUB_ENV
          fi

          chunkSize=$(( 8 * 1024 * 1024 ))
          index=0
          updatedFiles=0
          for product in $PRODUCTS; do
            echo -e "\n"
            activeJson=$( curl -s --header 'Referer: https://flash.android.com' "https://content-flashstation-pa.googleapis.com/v1/builds?product=$product&key=$APIKEY" | jq -c '.flashstationBuild.[] | select( .previewMetadata.active ) | .licenseText = [ "sure" ]' )
            jq '.' <<< "$activeJson"

            let index++

            # Error out if there are more than exactly one beta and one canary active
            activeNames=( $( jq -r '.releaseCandidateName' <<< "$activeJson" ) )
            canaryStatuses=$( jq -j '.previewMetadata.canary' <<< "$activeJson" )
            # if [[ "${#activeNames[@]}" -ne 2 || ( "$canaryStatuses" != "truefalse" && "$canaryStatuses" != "falsetrue" ) ]]; then exit 21; fi

            for name in ${activeNames[@]}; do
            resJson=$( jq -c --arg NAME "$name" '. | select( .releaseCandidateName == $NAME )' <<< "$activeJson" )

            propFile="${product%_*}.pif.prop"
            echo "$propFile"

            catalog="../catalog.json"

            if [[ -n $( jq '.previewMetadata.id' <<< "$resJson" | grep -i 'cinnamonbun-beta' ) ]]; then
              cd "$GITHUB_WORKSPACE/betas/cinnamonbun"
              type=$( jq -r '.previewMetadata.releaseTrackName' <<< "$resJson" | cut -d' ' -f2 )
              catalog="../../catalog.json"
            elif [[ $( jq -r '.previewMetadata.canary?' <<< "$resJson" ) == "false" ]]; then 
              cd "$GITHUB_WORKSPACE/betas"
              type=$( jq -r '.previewMetadata.releaseTrackName' <<< "$resJson" | cut -d' ' -f2 )
            else
              cd "$GITHUB_WORKSPACE/devices"
              type="CANARY"
            fi

            if [[ -e "$propFile" && $( jq -r '.releaseCandidateName?' <<< "$resJson" ) == $( grep 'FINGERPRINT' "$propFile" | cut -d= -f2 | cut -d/ -f4 ) ]]; then continue; fi

            zipUrl=$( jq -r '.factoryImageDownloadUrl' <<< "$resJson" )
            zipSize="$( curl -s --head $zipUrl | grep -i 'content-length' | cut -d' ' -f2 | tr -d '[[:space:]]' )"
            echo "$zipUrl"' - '"$zipSize"
            secDate=""
            fingerprint=""
            i=0
            startCh=0
            while [[ ( -z "$secDate" || -z "$fingerprint" ) && (( $( bc <<< "$startCh < $zipSize" ) )) ]]; do
              startCh=$(( $i * $chunkSize ))
              endCh=$(( ( $i + 1 ) * $chunkSize + 256 ))
              if [[ "$endCh" -gt "$zipSize" ]]; then endCh=$zipSize; fi
          
              statusCode=$( curl -s -v -o chunk.bin -H 'Accept-Encoding: identity' --connect-timeout 60 \
                      -H "Range: bytes=$startCh-$endCh" $zipUrl 2>&1 | grep '< HTTP/' | cut -d' ' -f3 )
              
              if [[ "$statusCode" -ne 206 && "$statusCode" -ne 200 ]]; then 
                echo "Partial download failed"
                wget -q --no-check-certificate -O full.zip --header 'Accept-Encoding: identity' "$zipUrl"
                break
              fi

              fingerT="$( grep -ia 'com.android.build.boot.fingerprint' chunk.bin  | strings | grep 'google.*keys$' )"
              if [[ -n "$fingerT" ]]; then fingerprint="$fingerT"; fi

              patchT="$( grep -ia 'com.android.build.boot.security_patch' chunk.bin | strings | grep '^2' )" # TODO: Update this in the year 3000
              if [[ -n "$patchT" ]]; then secDate="$patchT"; fi

              pv -S --size "$chunkSize" chunk.bin >> full.zip
              rm -f chunk.bin
          
              let i++
            done

            # Try scanning the entire file, just in case
            if [[ -z "$fingerprint" ]]; then fingerprint="$( grep -ia 'com.android.build.boot.fingerprint' full.zip | strings | grep 'google.*keys$' )"; fi
            if [[ -z "$secDate" ]]; then secDate="$( grep -ia 'com.android.build.boot.security_patch' full.zip | strings | grep '^2' )"; fi # TODO: Update this in the year 3000

            # zip is probably deflated. Attempt inflation
            if [[ -z "$secDate" || -z "$fingerprint" ]]; then
              unzip -j full.zip "*.zip"
              rm -f full.zip
              unzip -j image*.zip boot.img
              rm -f image*.zip

              if [[ -z "$fingerprint" ]]; then fingerprint="$( grep -ia 'com.android.build.boot.fingerprint' boot.img | strings | grep 'google.*keys$' )"; fi
              if [[ -z "$secDate" ]]; then secDate="$( grep -ia 'com.android.build.boot.security_patch' boot.img | strings | grep '^2' )"; fi # TODO: Update this in the year 3000

              rm -f boot.img
            fi

            if [[ -z "$fingerprint" ]]; then # Fallback to FP assembly
              fingerprint=google/$product/${product%_*}:$type/$( jq -r '.releaseCandidateName' <<< "$resJson" )/$( jq -r '.buildId' <<< "$resJson" ):user/release-keys
            fi

            if [[ -z "$secDate" ]]; then # Fallback to current month
              secDate="$( date +%Y-%m-05 )"
            fi 

            rm -f min.prop

          cat <<EOF | tee min.prop;
            MANUFACTURER=Google
            MODEL=$( jq -r --arg PR "${product%_*}" '.canaries.[$PR].name' "$catalog" )
            FINGERPRINT=$fingerprint
            PRODUCT=$product
            DEVICE=${product%_*}
            SECURITY_PATCH=$secDate
            DEVICE_INITIAL_SDK_INT=32
          EOF

            rm -f "$propFile"
            sh migrate.sh -f -a min.prop "$propFile"

            sed -i 's/spoofProvider=.*/spoofProvider=0/' "$propFile"

            echo "" >> "$propFile"
            echo "# Released: $( date '+%Y-%m-%d' )" >> "$propFile"
            echo "# Estimated Expiry: $( date -d @$(( $( date +%s ) + 60 * 60 * 24 * 7 * 6 )) '+%Y-%m-%d' )" >> "$propFile"
            echo "" >> "$propFile"
            echo "# previewMetadata:" >> "$propFile"
            echo '#   id: '$( jq -r '.previewMetadata.id' <<< "$resJson" ) >> "$propFile"
            echo '#   releaseTrackName: '$( jq -r '.previewMetadata.releaseTrackName' <<< "$resJson" ) >> "$propFile"
            echo '#   releaseTrackVersionName: '$( jq -r '.previewMetadata.releaseTrackVersionName' <<< "$resJson" ) >> "$propFile"
            echo "# Factory img: $zipUrl" >> "$propFile"

            if [[ "$type" == "CANARY" ]]; then typeJ="canaries"
            else typeJ="betas"; fi

            if [[ $( jq -c --arg T "$typeJ" --arg D "${product%_*}" '.[($T)].[($D)]' ) == "null" ]]; then
              jq --arg TYPE "$typeJ" --arg DEV "${product%_*}" --arg NAME "$( cat model.list | awk -v N=$index 'NR==N{ print }' )" \
                  '.[($TYPE)] += {($DEV):{"name":($NAME), "updated":"0", "releases":[]}}' "$catalog" > temp.json
              if [[ "$( wc -l < temp.json )" -gt 42 ]]; then mv -f temp.json "$catalog"; fi
            fi

            jq --arg TYPE "$typeJ" --arg DEV "${product%_*}" --arg SEC "$secDate" --arg T "$( date +%s )" \
               --arg REL "$( date '+%Y-%m-%d' )" --argjson RES "$resJson" \
               '.[($TYPE)].[($DEV)].updated = ($T) | .[($TYPE)].[($DEV)].releases += [{"releaseId":($RES | .previewMetadata.id), "target":($RES | .target), "buildName":($RES | .releaseCandidateName), "buildId":($RES | .buildId), "releaseDate":($REL), "securityDate":($SEC), "url":($RES | .factoryImageDownloadUrl)}]' \
               "$catalog" > temp.json
            if [[ "$( wc -l < temp.json )" -gt 42 ]]; then mv -f temp.json "$catalog"; fi

            git add "$propFile" "$catalog"
            let updatedFiles++

            done # for name in ${activeNames[@]}
          done

          echo "UPDATED_FILES=$updatedFiles" >> $GITHUB_ENV
          cd "$GITHUB_WORKSPACE"

      - name: Commit new props
        if: env.UPDATED_FILES > 0 && github.event_name != 'workflow_dispatch'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git commit -m "New build(s)"
          git push

      - name: Upload a Build Artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v6.0.0
        with:
          compression-level: 9
          name: output
          path: |
            devices/
            betas/
            catalog.json

      - name: Discord Notification
        if: env.UPDATED_FILES > 0 || env.NEWAPI > 0
        env:
          DISCORD_WH: ${{ secrets.DISCORD_WH }}
        run: |
          if [[ -z "$DISCORD_WH" ]]; then exit 0; fi

          if [[ "$UPDATED_FILES" -gt 0 ]]; then
            curl -s -X POST -o /dev/null -F 'payload_json="{\"content\":\"New Canaries/Betas!\"}"' "$DISCORD_WH"
          fi

          if [[ "$NEWAPI" -gt 0 ]]; then
            whdata="{\"content\":\"New API Key Found!\n$NEWAPIKEY\"}"
            curl -s -X POST -o /dev/null -F "payload_json=${whdata}" "$DISCORD_WH"
          fi
